spring:
  profiles:
    active: prod

  datasource:
    url: ${spring.datasoruce.url}   # ??? MySQL ??????? ??
    username: ${spring.datasource.username} # ?? MySQL ??? ??
    password: ${spring.datasource.password}  # ?? MySQL ????
    driver-class-name: ${spring.datasource.driver-class-name} # MySQL ???? ???

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update     # ??? ?? ?? (create, update, validate, none ? ? 1)
    show-sql: true         # ???? SQL? ??? ??
    properties:
      hibernate:
        format_sql: false   # SQL ??? ?? ?? ?? (???)
        show_sql: true     # ??? ???? SQL ??? ???
        use_sql_comments: true
    open-in-view: false    # OSIV(Open Session In View) ????


logging:
  level:
    org.hibernate.SQL: debug                  # ???? SQL ?? ??
    org.hibernate.type.descriptor.sql: trace  # ???? ???? ? ?? ??

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-milliseconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_MILLISECONDS}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}